import {
  Wallet, Receipt, Target, BarChart2, Bot, Zap, Utensils, Bus,
  Gamepad2, RefreshCw, MoreHorizontal, Briefcase, Gift, Rocket,
  Menu, X, MessageSquare, ChevronRight, ArrowRight, Sparkles,
  TrendingUp, TrendingDown, Shield, Check, CheckCircle, DollarSign,
  PiggyBank, CreditCard, Banknote, LayoutDashboard, User, Settings,
  Bell, Lock, Eye, EyeOff, Plus, Minus, Trash2, Edit2, Search,
  Calendar, Clock, Info, AlertTriangle, XCircle, LogOut, Star,
  Circle, BarChart, LineChart, PieChart, Activity, Home, BookOpen,
  Lightbulb, HeartHandshake, Repeat, Send, Brain,
} from 'lucide-react';

const iconMap = {
  wallet: Wallet,
  allowance: Wallet,
  receipt: Receipt,
  target: Target,
  'bar-chart': BarChart2,
  chart: BarChart2,
  bot: Bot,
  robot: Bot,
  brain: Brain,
  zap: Zap,
  utensils: Utensils,
  food: Utensils,
  bus: Bus,
  transport: Bus,
  gamepad: Gamepad2,
  entertainment: Gamepad2,
  repeat: RefreshCw,
  subscriptions: RefreshCw,
  'more-horizontal': MoreHorizontal,
  other: MoreHorizontal,
  briefcase: Briefcase,
  job: Briefcase,
  gift: Gift,
  rocket: Rocket,
  side: Rocket,
  menu: Menu,
  x: X,
  close: X,
  'message-square': MessageSquare,
  chat: MessageSquare,
  'chevron-right': ChevronRight,
  'arrow-right': ArrowRight,
  sparkles: Sparkles,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  shield: Shield,
  check: Check,
  'check-circle': CheckCircle,
  'dollar-sign': DollarSign,
  'piggy-bank': PiggyBank,
  'credit-card': CreditCard,
  banknote: Banknote,
  dashboard: LayoutDashboard,
  user: User,
  settings: Settings,
  bell: Bell,
  lock: Lock,
  eye: Eye,
  'eye-off': EyeOff,
  plus: Plus,
  minus: Minus,
  trash: Trash2,
  edit: Edit2,
  search: Search,
  calendar: Calendar,
  clock: Clock,
  info: Info,
  alert: AlertTriangle,
  'x-circle': XCircle,
  logout: LogOut,
  star: Star,
  'bar-chart-2': BarChart2,
  'line-chart': LineChart,
  'pie-chart': PieChart,
  activity: Activity,
  home: Home,
  book: BookOpen,
  lightbulb: Lightbulb,
  heart: HeartHandshake,
  send: Send,
};

export default function Icon({ name = 'circle', size = 20, className = '', strokeWidth = 1.75 }) {
  const Comp = iconMap[name] || Circle;
  return <Comp size={size} className={className} strokeWidth={strokeWidth} />;
}
